<?php


namespace admin\models;


use yii\db\ActiveRecord;

class Articles extends ActiveRecord
{
    public static function tableName()
    {
        return 'articles'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [['title','category_id','content'],'required'],
            ['id','safe']
        ];
    }
}