<?php

namespace admin\models;

class Categories extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'categories'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [['title'],'required'],
            [['id'],'safe']
        ];
    }
    public function attributeLabels()
    {
        return [
            'title' => 'Название'
        ]; // TODO: Change the autogenerated stub
    }

    public function getUsers()
    {
        return $this->hasMany(User::className(), ['category_id' => 'id']);
    }
}