<?php


namespace admin\models;


use yii\db\ActiveRecord;

class User extends ActiveRecord
{
    public static function tableName()
    {
        return 'user'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [['username','password_hash'],'required'],
            [['email','status'],'safe'],
        ];
    }
    public function beforeSave($insert)
    {
        if($this->isNewRecord){
            $this->created_at = date("Y/m/d h:m:s");
            $this->auth_key = \Yii::$app->security->generateRandomString();
        } else{
            $this->updated_at = date("Y/m/d h:m:s");
        }

        $this->password_hash = \Yii::$app->security->generatePasswordHash($this->password_hash);

        return true;
    }

}