<?php


namespace admin\models;

use yii\db\ActiveRecord;

class User extends ActiveRecord
{

    public static $roles = [
        'admin'=>'admin',
        'user'=>'user'
    ];
    public static function tableName()
    {
        return 'user'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [['username','password_hash','role','first_name','last_name','job','category_id'],'required'],
            [['email','status','phone_number','date_of_birth','full_name'],'safe'],
            [['image'],'file','skipOnEmpty' => true, 'extensions' => ['png, jpg, jpeg']]
        ];
    }
    public function upload(){
        if ($this->validate()) {
            $this->image->saveAs('/frontend/web/assets/images/' . \Yii::$app->user->identity->username . '.' . $this->image->extension);
            return true;
        } else {
            return false;
        }
    }
    public function attributeLabels()
    {
        return [
            'username'=>'Логин',
            'first_name'=>'Имя',
            'last_name'=>'Фамилия',
            'category_id'=>'Категория',
            'job'=>'Должность',
            'password_hash'=>'Хэш код пароля',
            'role'=>'Роль',
            'created_at'=>'Создано',
            'updated_at'=>'Обновлено',
        ]; // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        if($this->isNewRecord){
            $this->created_at = date("d/m/Y");
            $this->auth_key = \Yii::$app->security->generateRandomString();
            $this->password_hash = \Yii::$app->security->generatePasswordHash($this->password_hash);
            if (!$this->image){
                $this->image = 'nopicture.png';
            }
            $this->full_name = $this->first_name .' '.$this->last_name;
        } else{
            if (!User::findOne(['password_hash'=>$this->password_hash])){
                $this->password_hash = \Yii::$app->security->generatePasswordHash($this->password_hash);
            }
            $this->updated_at = date("d/m/Y");
        }
        return true;
    }

}