<?php


namespace admin\models;


use yii\db\ActiveRecord;

class User extends ActiveRecord
{
    public static $roles = [
        'admin'=>'admin',
        'user'=>'user'
    ];
    public static function tableName()
    {
        return 'user'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [['username','password_hash','role'],'required'],
            [['email','status','image','phone_number'],'safe'],
        ];
    }
    public function attributeLabels()
    {
        return [
            'username'=>'Имя',
            'password_hash'=>'Хэш код пароля',
            'role'=>'Роль',
            'created_at'=>'Создано',
            'updated_at'=>'Обновлено',
        ]; // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        if($this->isNewRecord){
            $this->created_at = date("Y/m/d h:m:s");
            $this->auth_key = \Yii::$app->security->generateRandomString();
            $this->password_hash = \Yii::$app->security->generatePasswordHash($this->password_hash);
            if (!$this->image){
                $this->image = 'nopicture.png';
            }
        } else{
            if (!User::findOne(['password_hash'=>$this->password_hash])){
                $this->password_hash = \Yii::$app->security->generatePasswordHash($this->password_hash);
            }
            $this->updated_at = date("Y/m/d h:m:s");
        }
        return true;
    }

}