<?php


namespace frontend\models;


use Yii;
use yii\db\ActiveRecord;

class Comments extends ActiveRecord
{
    public static function tableName()
    {
        return 'comments'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [['id','created_at','user','article_id'], 'safe'],
            [['comment'], 'required']
        ]; // TODO: Change the autogenerated stub
    }
    public function beforeSave($insert)
    {
        if ($this->isNewRecord){
            $this->created_at = date('Y-m-d h:m:s'); // TODO: Change the autogenerated stub
        }
        return true;
    }
}