<?php


namespace frontend\models;


use admin\models\Categories;
use admin\models\User;
use Cassandra\Date;
use yii\db\ActiveRecord;

class Requests extends ActiveRecord
{
    public $statuses = [
        1 => 'В ожидании',
        2 => 'Принято',
        3 => 'Завершено'
    ];
    public static function tableName()
    {
        return 'requests'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [['to_users_id','date','category_id'],'required'],
            [['from_user_id','status','docs','created_at'], 'safe']
        ]; // TODO: Change the autogenerated stub
    }
    public function beforeSave($insert)
    {
        if ($this->isNewRecord){
            $date = date('d/m/Y');
            $this->created_at = $date;
        }; // TODO: Change the autogenerated stub
        return true;
    }

    public function getCategory()
    {
        return $this->hasMany(Categories::class, ['id'=>'category_id']);
    }
    public function getFromUser()
    {
        return $this->hasMany(User::class, ['id'=>'from_user_id']);
    }
    public function getToUsers()
    {
        $usersIds = explode(",", $this->to_users_id);
        $users = array();
        foreach ($usersIds as $userId){
            $user = User::findOne(['id'=>$userId]);
            array_push($users, ['id'=>$user->id,'full_name'=>$user->full_name]);
        }
        return $users;
    }
}